version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nanosurvey
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
